// GENERATED FILE — do not edit by hand.
// Regenerate with: node scripts/generate-language-names.mjs
// (edit scripts/generate-language-names.mjs instead, then re-run it)

/// Localized display name of `target_language` as it would be shown to a `ui_lang`
/// speaker. Known EU language codes resolve via the generated tables below; free text (a
/// user-typed "other language") is returned exactly as given, trimmed. Must stay
/// byte-identical to languageDisplayName in frontend/src/languageNames.ts (both are
/// generated from the same Intl.DisplayNames data by generate-language-names.mjs) so the
/// two sides fill the same "{lang}" placeholder identically into the default translation
/// prompts.
pub fn language_display_name(ui_lang: &str, target_language: &str) -> String {
    let trimmed = target_language.trim();
    let lower = trimmed.to_ascii_lowercase();
    let table: &[(&str, &str)] = match ui_lang {
        "bg" => &BG_NAMES,
        "cs" => &CS_NAMES,
        "da" => &DA_NAMES,
        "de" => &DE_NAMES,
        "el" => &EL_NAMES,
        "en" => &EN_NAMES,
        "es" => &ES_NAMES,
        "et" => &ET_NAMES,
        "fi" => &FI_NAMES,
        "fr" => &FR_NAMES,
        "ga" => &GA_NAMES,
        "hr" => &HR_NAMES,
        "hu" => &HU_NAMES,
        "it" => &IT_NAMES,
        "lt" => &LT_NAMES,
        "lv" => &LV_NAMES,
        "mt" => &MT_NAMES,
        "nl" => &NL_NAMES,
        "pl" => &PL_NAMES,
        "pt" => &PT_NAMES,
        "ro" => &RO_NAMES,
        "sk" => &SK_NAMES,
        "sl" => &SL_NAMES,
        "sv" => &SV_NAMES,
        _ => &EN_NAMES,
    };
    table
        .iter()
        .find(|(code, _)| *code == lower)
        .map(|(_, name)| name.to_string())
        .unwrap_or_else(|| trimmed.to_string())
}

const BG_NAMES: [(&str, &str); 24] = [
    ("bg", "български"),
    ("cs", "чешки"),
    ("da", "датски"),
    ("de", "немски"),
    ("el", "гръцки"),
    ("en", "английски"),
    ("es", "испански"),
    ("et", "естонски"),
    ("fi", "фински"),
    ("fr", "френски"),
    ("ga", "ирландски"),
    ("hr", "хърватски"),
    ("hu", "унгарски"),
    ("it", "италиански"),
    ("lt", "литовски"),
    ("lv", "латвийски"),
    ("mt", "малтийски"),
    ("nl", "нидерландски"),
    ("pl", "полски"),
    ("pt", "португалски"),
    ("ro", "румънски"),
    ("sk", "словашки"),
    ("sl", "словенски"),
    ("sv", "шведски"),
];

const CS_NAMES: [(&str, &str); 24] = [
    ("bg", "bulharština"),
    ("cs", "čeština"),
    ("da", "dánština"),
    ("de", "němčina"),
    ("el", "řečtina"),
    ("en", "angličtina"),
    ("es", "španělština"),
    ("et", "estonština"),
    ("fi", "finština"),
    ("fr", "francouzština"),
    ("ga", "irština"),
    ("hr", "chorvatština"),
    ("hu", "maďarština"),
    ("it", "italština"),
    ("lt", "litevština"),
    ("lv", "lotyština"),
    ("mt", "maltština"),
    ("nl", "nizozemština"),
    ("pl", "polština"),
    ("pt", "portugalština"),
    ("ro", "rumunština"),
    ("sk", "slovenština"),
    ("sl", "slovinština"),
    ("sv", "švédština"),
];

const DA_NAMES: [(&str, &str); 24] = [
    ("bg", "bulgarsk"),
    ("cs", "tjekkisk"),
    ("da", "dansk"),
    ("de", "tysk"),
    ("el", "græsk"),
    ("en", "engelsk"),
    ("es", "spansk"),
    ("et", "estisk"),
    ("fi", "finsk"),
    ("fr", "fransk"),
    ("ga", "irsk"),
    ("hr", "kroatisk"),
    ("hu", "ungarsk"),
    ("it", "italiensk"),
    ("lt", "litauisk"),
    ("lv", "lettisk"),
    ("mt", "maltesisk"),
    ("nl", "nederlandsk"),
    ("pl", "polsk"),
    ("pt", "portugisisk"),
    ("ro", "rumænsk"),
    ("sk", "slovakisk"),
    ("sl", "slovensk"),
    ("sv", "svensk"),
];

const DE_NAMES: [(&str, &str); 24] = [
    ("bg", "Bulgarisch"),
    ("cs", "Tschechisch"),
    ("da", "Dänisch"),
    ("de", "Deutsch"),
    ("el", "Griechisch"),
    ("en", "Englisch"),
    ("es", "Spanisch"),
    ("et", "Estnisch"),
    ("fi", "Finnisch"),
    ("fr", "Französisch"),
    ("ga", "Irisch"),
    ("hr", "Kroatisch"),
    ("hu", "Ungarisch"),
    ("it", "Italienisch"),
    ("lt", "Litauisch"),
    ("lv", "Lettisch"),
    ("mt", "Maltesisch"),
    ("nl", "Niederländisch"),
    ("pl", "Polnisch"),
    ("pt", "Portugiesisch"),
    ("ro", "Rumänisch"),
    ("sk", "Slowakisch"),
    ("sl", "Slowenisch"),
    ("sv", "Schwedisch"),
];

const EL_NAMES: [(&str, &str); 24] = [
    ("bg", "Βουλγαρικά"),
    ("cs", "Τσεχικά"),
    ("da", "Δανικά"),
    ("de", "Γερμανικά"),
    ("el", "Ελληνικά"),
    ("en", "Αγγλικά"),
    ("es", "Ισπανικά"),
    ("et", "Εσθονικά"),
    ("fi", "Φινλανδικά"),
    ("fr", "Γαλλικά"),
    ("ga", "Ιρλανδικά"),
    ("hr", "Κροατικά"),
    ("hu", "Ουγγρικά"),
    ("it", "Ιταλικά"),
    ("lt", "Λιθουανικά"),
    ("lv", "Λετονικά"),
    ("mt", "Μαλτεζικά"),
    ("nl", "Ολλανδικά"),
    ("pl", "Πολωνικά"),
    ("pt", "Πορτογαλικά"),
    ("ro", "Ρουμανικά"),
    ("sk", "Σλοβακικά"),
    ("sl", "Σλοβενικά"),
    ("sv", "Σουηδικά"),
];

const EN_NAMES: [(&str, &str); 24] = [
    ("bg", "Bulgarian"),
    ("cs", "Czech"),
    ("da", "Danish"),
    ("de", "German"),
    ("el", "Greek"),
    ("en", "English"),
    ("es", "Spanish"),
    ("et", "Estonian"),
    ("fi", "Finnish"),
    ("fr", "French"),
    ("ga", "Irish"),
    ("hr", "Croatian"),
    ("hu", "Hungarian"),
    ("it", "Italian"),
    ("lt", "Lithuanian"),
    ("lv", "Latvian"),
    ("mt", "Maltese"),
    ("nl", "Dutch"),
    ("pl", "Polish"),
    ("pt", "Portuguese"),
    ("ro", "Romanian"),
    ("sk", "Slovak"),
    ("sl", "Slovenian"),
    ("sv", "Swedish"),
];

const ES_NAMES: [(&str, &str); 24] = [
    ("bg", "búlgaro"),
    ("cs", "checo"),
    ("da", "danés"),
    ("de", "alemán"),
    ("el", "griego"),
    ("en", "inglés"),
    ("es", "español"),
    ("et", "estonio"),
    ("fi", "finés"),
    ("fr", "francés"),
    ("ga", "irlandés"),
    ("hr", "croata"),
    ("hu", "húngaro"),
    ("it", "italiano"),
    ("lt", "lituano"),
    ("lv", "letón"),
    ("mt", "maltés"),
    ("nl", "neerlandés"),
    ("pl", "polaco"),
    ("pt", "portugués"),
    ("ro", "rumano"),
    ("sk", "eslovaco"),
    ("sl", "esloveno"),
    ("sv", "sueco"),
];

const ET_NAMES: [(&str, &str); 24] = [
    ("bg", "bulgaaria"),
    ("cs", "tšehhi"),
    ("da", "taani"),
    ("de", "saksa"),
    ("el", "kreeka"),
    ("en", "inglise"),
    ("es", "hispaania"),
    ("et", "eesti"),
    ("fi", "soome"),
    ("fr", "prantsuse"),
    ("ga", "iiri"),
    ("hr", "horvaadi"),
    ("hu", "ungari"),
    ("it", "itaalia"),
    ("lt", "leedu"),
    ("lv", "läti"),
    ("mt", "malta"),
    ("nl", "hollandi"),
    ("pl", "poola"),
    ("pt", "portugali"),
    ("ro", "rumeenia"),
    ("sk", "slovaki"),
    ("sl", "sloveeni"),
    ("sv", "rootsi"),
];

const FI_NAMES: [(&str, &str); 24] = [
    ("bg", "bulgaria"),
    ("cs", "tšekki"),
    ("da", "tanska"),
    ("de", "saksa"),
    ("el", "kreikka"),
    ("en", "englanti"),
    ("es", "espanja"),
    ("et", "viro"),
    ("fi", "suomi"),
    ("fr", "ranska"),
    ("ga", "iiri"),
    ("hr", "kroatia"),
    ("hu", "unkari"),
    ("it", "italia"),
    ("lt", "liettua"),
    ("lv", "latvia"),
    ("mt", "malta"),
    ("nl", "hollanti"),
    ("pl", "puola"),
    ("pt", "portugali"),
    ("ro", "romania"),
    ("sk", "slovakki"),
    ("sl", "sloveeni"),
    ("sv", "ruotsi"),
];

const FR_NAMES: [(&str, &str); 24] = [
    ("bg", "bulgare"),
    ("cs", "tchèque"),
    ("da", "danois"),
    ("de", "allemand"),
    ("el", "grec"),
    ("en", "anglais"),
    ("es", "espagnol"),
    ("et", "estonien"),
    ("fi", "finnois"),
    ("fr", "français"),
    ("ga", "irlandais"),
    ("hr", "croate"),
    ("hu", "hongrois"),
    ("it", "italien"),
    ("lt", "lituanien"),
    ("lv", "letton"),
    ("mt", "maltais"),
    ("nl", "néerlandais"),
    ("pl", "polonais"),
    ("pt", "portugais"),
    ("ro", "roumain"),
    ("sk", "slovaque"),
    ("sl", "slovène"),
    ("sv", "suédois"),
];

const GA_NAMES: [(&str, &str); 24] = [
    ("bg", "Bulgáiris"),
    ("cs", "Seicis"),
    ("da", "Danmhairgis"),
    ("de", "Gearmáinis"),
    ("el", "Gréigis"),
    ("en", "Béarla"),
    ("es", "Spáinnis"),
    ("et", "Eastóinis"),
    ("fi", "Fionlainnis"),
    ("fr", "Fraincis"),
    ("ga", "Gaeilge"),
    ("hr", "Cróitis"),
    ("hu", "Ungáiris"),
    ("it", "Iodáilis"),
    ("lt", "Liotuáinis"),
    ("lv", "Laitvis"),
    ("mt", "Máltais"),
    ("nl", "Ollainnis"),
    ("pl", "Polainnis"),
    ("pt", "Portaingéilis"),
    ("ro", "Rómáinis"),
    ("sk", "Slóvaicis"),
    ("sl", "Slóivéinis"),
    ("sv", "Sualainnis"),
];

const HR_NAMES: [(&str, &str); 24] = [
    ("bg", "bugarski"),
    ("cs", "češki"),
    ("da", "danski"),
    ("de", "njemački"),
    ("el", "grčki"),
    ("en", "engleski"),
    ("es", "španjolski"),
    ("et", "estonski"),
    ("fi", "finski"),
    ("fr", "francuski"),
    ("ga", "irski"),
    ("hr", "hrvatski"),
    ("hu", "mađarski"),
    ("it", "talijanski"),
    ("lt", "litavski"),
    ("lv", "latvijski"),
    ("mt", "malteški"),
    ("nl", "nizozemski"),
    ("pl", "poljski"),
    ("pt", "portugalski"),
    ("ro", "rumunjski"),
    ("sk", "slovački"),
    ("sl", "slovenski"),
    ("sv", "švedski"),
];

const HU_NAMES: [(&str, &str); 24] = [
    ("bg", "bolgár"),
    ("cs", "cseh"),
    ("da", "dán"),
    ("de", "német"),
    ("el", "görög"),
    ("en", "angol"),
    ("es", "spanyol"),
    ("et", "észt"),
    ("fi", "finn"),
    ("fr", "francia"),
    ("ga", "ír"),
    ("hr", "horvát"),
    ("hu", "magyar"),
    ("it", "olasz"),
    ("lt", "litván"),
    ("lv", "lett"),
    ("mt", "máltai"),
    ("nl", "holland"),
    ("pl", "lengyel"),
    ("pt", "portugál"),
    ("ro", "román"),
    ("sk", "szlovák"),
    ("sl", "szlovén"),
    ("sv", "svéd"),
];

const IT_NAMES: [(&str, &str); 24] = [
    ("bg", "bulgaro"),
    ("cs", "ceco"),
    ("da", "danese"),
    ("de", "tedesco"),
    ("el", "greco"),
    ("en", "inglese"),
    ("es", "spagnolo"),
    ("et", "estone"),
    ("fi", "finlandese"),
    ("fr", "francese"),
    ("ga", "irlandese"),
    ("hr", "croato"),
    ("hu", "ungherese"),
    ("it", "italiano"),
    ("lt", "lituano"),
    ("lv", "lettone"),
    ("mt", "maltese"),
    ("nl", "olandese"),
    ("pl", "polacco"),
    ("pt", "portoghese"),
    ("ro", "rumeno"),
    ("sk", "slovacco"),
    ("sl", "sloveno"),
    ("sv", "svedese"),
];

const LT_NAMES: [(&str, &str); 24] = [
    ("bg", "bulgarų"),
    ("cs", "čekų"),
    ("da", "danų"),
    ("de", "vokiečių"),
    ("el", "graikų"),
    ("en", "anglų"),
    ("es", "ispanų"),
    ("et", "estų"),
    ("fi", "suomių"),
    ("fr", "prancūzų"),
    ("ga", "airių"),
    ("hr", "kroatų"),
    ("hu", "vengrų"),
    ("it", "italų"),
    ("lt", "lietuvių"),
    ("lv", "latvių"),
    ("mt", "maltiečių"),
    ("nl", "olandų"),
    ("pl", "lenkų"),
    ("pt", "portugalų"),
    ("ro", "rumunų"),
    ("sk", "slovakų"),
    ("sl", "slovėnų"),
    ("sv", "švedų"),
];

const LV_NAMES: [(&str, &str); 24] = [
    ("bg", "bulgāru"),
    ("cs", "čehu"),
    ("da", "dāņu"),
    ("de", "vācu"),
    ("el", "grieķu"),
    ("en", "angļu"),
    ("es", "spāņu"),
    ("et", "igauņu"),
    ("fi", "somu"),
    ("fr", "franču"),
    ("ga", "īru"),
    ("hr", "horvātu"),
    ("hu", "ungāru"),
    ("it", "itāļu"),
    ("lt", "lietuviešu"),
    ("lv", "latviešu"),
    ("mt", "maltiešu"),
    ("nl", "holandiešu"),
    ("pl", "poļu"),
    ("pt", "portugāļu"),
    ("ro", "rumāņu"),
    ("sk", "slovāku"),
    ("sl", "slovēņu"),
    ("sv", "zviedru"),
];

const MT_NAMES: [(&str, &str); 24] = [
    ("bg", "Bulgaru"),
    ("cs", "Ċek"),
    ("da", "Daniż"),
    ("de", "Ġermaniż"),
    ("el", "Grieg"),
    ("en", "Ingliż"),
    ("es", "Spanjol"),
    ("et", "Estonjan"),
    ("fi", "Finlandiż"),
    ("fr", "Franċiż"),
    ("ga", "Irlandiż"),
    ("hr", "Kroat"),
    ("hu", "Ungeriż"),
    ("it", "Taljan"),
    ("lt", "Litwan"),
    ("lv", "Latvjan"),
    ("mt", "Malti"),
    ("nl", "Olandiż"),
    ("pl", "Pollakk"),
    ("pt", "Portugiż"),
    ("ro", "Rumen"),
    ("sk", "Slovakk"),
    ("sl", "Sloven"),
    ("sv", "Żvediż"),
];

const NL_NAMES: [(&str, &str); 24] = [
    ("bg", "Bulgaars"),
    ("cs", "Tsjechisch"),
    ("da", "Deens"),
    ("de", "Duits"),
    ("el", "Grieks"),
    ("en", "Engels"),
    ("es", "Spaans"),
    ("et", "Estisch"),
    ("fi", "Fins"),
    ("fr", "Frans"),
    ("ga", "Iers"),
    ("hr", "Kroatisch"),
    ("hu", "Hongaars"),
    ("it", "Italiaans"),
    ("lt", "Litouws"),
    ("lv", "Lets"),
    ("mt", "Maltees"),
    ("nl", "Nederlands"),
    ("pl", "Pools"),
    ("pt", "Portugees"),
    ("ro", "Roemeens"),
    ("sk", "Slowaaks"),
    ("sl", "Sloveens"),
    ("sv", "Zweeds"),
];

const PL_NAMES: [(&str, &str); 24] = [
    ("bg", "bułgarski"),
    ("cs", "czeski"),
    ("da", "duński"),
    ("de", "niemiecki"),
    ("el", "grecki"),
    ("en", "angielski"),
    ("es", "hiszpański"),
    ("et", "estoński"),
    ("fi", "fiński"),
    ("fr", "francuski"),
    ("ga", "irlandzki"),
    ("hr", "chorwacki"),
    ("hu", "węgierski"),
    ("it", "włoski"),
    ("lt", "litewski"),
    ("lv", "łotewski"),
    ("mt", "maltański"),
    ("nl", "niderlandzki"),
    ("pl", "polski"),
    ("pt", "portugalski"),
    ("ro", "rumuński"),
    ("sk", "słowacki"),
    ("sl", "słoweński"),
    ("sv", "szwedzki"),
];

const PT_NAMES: [(&str, &str); 24] = [
    ("bg", "búlgaro"),
    ("cs", "tcheco"),
    ("da", "dinamarquês"),
    ("de", "alemão"),
    ("el", "grego"),
    ("en", "inglês"),
    ("es", "espanhol"),
    ("et", "estoniano"),
    ("fi", "finlandês"),
    ("fr", "francês"),
    ("ga", "irlandês"),
    ("hr", "croata"),
    ("hu", "húngaro"),
    ("it", "italiano"),
    ("lt", "lituano"),
    ("lv", "letão"),
    ("mt", "maltês"),
    ("nl", "holandês"),
    ("pl", "polonês"),
    ("pt", "português"),
    ("ro", "romeno"),
    ("sk", "eslovaco"),
    ("sl", "esloveno"),
    ("sv", "sueco"),
];

const RO_NAMES: [(&str, &str); 24] = [
    ("bg", "bulgară"),
    ("cs", "cehă"),
    ("da", "daneză"),
    ("de", "germană"),
    ("el", "greacă"),
    ("en", "engleză"),
    ("es", "spaniolă"),
    ("et", "estonă"),
    ("fi", "finlandeză"),
    ("fr", "franceză"),
    ("ga", "irlandeză"),
    ("hr", "croată"),
    ("hu", "maghiară"),
    ("it", "italiană"),
    ("lt", "lituaniană"),
    ("lv", "letonă"),
    ("mt", "malteză"),
    ("nl", "neerlandeză"),
    ("pl", "poloneză"),
    ("pt", "portugheză"),
    ("ro", "română"),
    ("sk", "slovacă"),
    ("sl", "slovenă"),
    ("sv", "suedeză"),
];

const SK_NAMES: [(&str, &str); 24] = [
    ("bg", "bulharčina"),
    ("cs", "čeština"),
    ("da", "dánčina"),
    ("de", "nemčina"),
    ("el", "gréčtina"),
    ("en", "angličtina"),
    ("es", "španielčina"),
    ("et", "estónčina"),
    ("fi", "fínčina"),
    ("fr", "francúzština"),
    ("ga", "írčina"),
    ("hr", "chorvátčina"),
    ("hu", "maďarčina"),
    ("it", "taliančina"),
    ("lt", "litovčina"),
    ("lv", "lotyština"),
    ("mt", "maltčina"),
    ("nl", "holandčina"),
    ("pl", "poľština"),
    ("pt", "portugalčina"),
    ("ro", "rumunčina"),
    ("sk", "slovenčina"),
    ("sl", "slovinčina"),
    ("sv", "švédčina"),
];

const SL_NAMES: [(&str, &str); 24] = [
    ("bg", "bolgarščina"),
    ("cs", "češčina"),
    ("da", "danščina"),
    ("de", "nemščina"),
    ("el", "grščina"),
    ("en", "angleščina"),
    ("es", "španščina"),
    ("et", "estonščina"),
    ("fi", "finščina"),
    ("fr", "francoščina"),
    ("ga", "irščina"),
    ("hr", "hrvaščina"),
    ("hu", "madžarščina"),
    ("it", "italijanščina"),
    ("lt", "litovščina"),
    ("lv", "latvijščina"),
    ("mt", "malteščina"),
    ("nl", "nizozemščina"),
    ("pl", "poljščina"),
    ("pt", "portugalščina"),
    ("ro", "romunščina"),
    ("sk", "slovaščina"),
    ("sl", "slovenščina"),
    ("sv", "švedščina"),
];

const SV_NAMES: [(&str, &str); 24] = [
    ("bg", "bulgariska"),
    ("cs", "tjeckiska"),
    ("da", "danska"),
    ("de", "tyska"),
    ("el", "grekiska"),
    ("en", "engelska"),
    ("es", "spanska"),
    ("et", "estniska"),
    ("fi", "finska"),
    ("fr", "franska"),
    ("ga", "iriska"),
    ("hr", "kroatiska"),
    ("hu", "ungerska"),
    ("it", "italienska"),
    ("lt", "litauiska"),
    ("lv", "lettiska"),
    ("mt", "maltesiska"),
    ("nl", "nederländska"),
    ("pl", "polska"),
    ("pt", "portugisiska"),
    ("ro", "rumänska"),
    ("sk", "slovakiska"),
    ("sl", "slovenska"),
    ("sv", "svenska"),
];
